export default {
    TOGGLE: 'TOGGLE',

    GET_ABOUT: 'GET_ABOUT',
    GET_ABOUT_ERROR: 'GET_ABOUT_ERROR',

    GET_EXPERİENCE: 'GET_EXPERİENCE',
    GET_EXPERİENCE_ERROR: 'GET_EXPERİENCE_ERROR',

    GET_EDUCATION: 'GET_EDUCATION',
    GET_EDUCATION_ERROR: 'GET_EDUCATION_ERROR',

    GET_PORTFOLIOS: 'GET_PORTFOLIOS',
    GET_PORTFOLIOS_ERROR: 'GET_PORTFOLIOS_ERROR',

    GET_BLOGS: 'GET_BLOGS',
    GET_BLOGS_ERROR: 'GET_BLOGS_ERROR',

    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_CATEGORIES_ERROR: 'GET_CATEGORIES_ERROR',

    GET_SKILLS: 'GET_SKILLS',
    GET_SKILLS_ERROR: 'GET_SKILLS_ERROR',
}
